os:
  - linux

language: php

php:
  - '7.1'
  - '7.2'

before_script:
  - composer install --no-interaction

notifications:
  email: false

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs --standard=PSR2 ./src

after_success:
  - travis_retry php vendor/bin/coveralls -v