os:
  - linux

language: php

php:
  - '7.1'
  - '7.2'

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs --standard=PSR2 ./src

after_success:
  - travis_retry php vendor/bin/coveralls -v